title: Eigenvector
logo: /assets/img/logo.png
description: Financial infrastructure
show_downloads: false
github:
  is_user_page: false
  is_project_page: false
google_analytics:
theme: jekyll-theme-minimal
